// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.0
// source: odbc.proto

package odbc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DummyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DummyReq) Reset() {
	*x = DummyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odbc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DummyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyReq) ProtoMessage() {}

func (x *DummyReq) ProtoReflect() protoreflect.Message {
	mi := &file_odbc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyReq.ProtoReflect.Descriptor instead.
func (*DummyReq) Descriptor() ([]byte, []int) {
	return file_odbc_proto_rawDescGZIP(), []int{0}
}

type XactRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsolationLevel int32 `protobuf:"varint,1,opt,name=isolation_level,json=isolationLevel,proto3" json:"isolation_level,omitempty"`
	ReadOnly       bool  `protobuf:"varint,2,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"` //    bool  atomic          = 3;
}

func (x *XactRequest) Reset() {
	*x = XactRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odbc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XactRequest) ProtoMessage() {}

func (x *XactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_odbc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XactRequest.ProtoReflect.Descriptor instead.
func (*XactRequest) Descriptor() ([]byte, []int) {
	return file_odbc_proto_rawDescGZIP(), []int{1}
}

func (x *XactRequest) GetIsolationLevel() int32 {
	if x != nil {
		return x.IsolationLevel
	}
	return 0
}

func (x *XactRequest) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type XactResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XactId  uint64 `protobuf:"varint,1,opt,name=xact_id,json=xactId,proto3" json:"xact_id,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *XactResponse) Reset() {
	*x = XactResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odbc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XactResponse) ProtoMessage() {}

func (x *XactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_odbc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XactResponse.ProtoReflect.Descriptor instead.
func (*XactResponse) Descriptor() ([]byte, []int) {
	return file_odbc_proto_rawDescGZIP(), []int{2}
}

func (x *XactResponse) GetXactId() uint64 {
	if x != nil {
		return x.XactId
	}
	return 0
}

func (x *XactResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_odbc_proto protoreflect.FileDescriptor

var file_odbc_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6f, 0x64, 0x62, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x73,
	0x71, 0x6c, 0x22, 0x0a, 0x0a, 0x08, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x22, 0x53,
	0x0a, 0x0b, 0x58, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a,
	0x0f, 0x69, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x69, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x6f,
	0x6e, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x4f,
	0x6e, 0x6c, 0x79, 0x22, 0x41, 0x0a, 0x0c, 0x58, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x78, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x78, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x3e, 0x0a, 0x0a, 0x4d, 0x44, 0x42, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x11, 0x2e,
	0x62, 0x73, 0x71, 0x6c, 0x2e, 0x58, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x62, 0x73, 0x71, 0x6c, 0x2e, 0x58, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2f,
	0x75, 0x74, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x6f, 0x64, 0x62, 0x63, 0x2f, 0x6d,
	0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x42, 0x75, 0x66, 0x66, 0x65,
	0x72, 0x73, 0x2f, 0x6f, 0x64, 0x62, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_odbc_proto_rawDescOnce sync.Once
	file_odbc_proto_rawDescData = file_odbc_proto_rawDesc
)

func file_odbc_proto_rawDescGZIP() []byte {
	file_odbc_proto_rawDescOnce.Do(func() {
		file_odbc_proto_rawDescData = protoimpl.X.CompressGZIP(file_odbc_proto_rawDescData)
	})
	return file_odbc_proto_rawDescData
}

var file_odbc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_odbc_proto_goTypes = []interface{}{
	(*DummyReq)(nil),     // 0: bsql.DummyReq
	(*XactRequest)(nil),  // 1: bsql.XactRequest
	(*XactResponse)(nil), // 2: bsql.XactResponse
}
var file_odbc_proto_depIdxs = []int32{
	1, // 0: bsql.MDBService.Begin:input_type -> bsql.XactRequest
	2, // 1: bsql.MDBService.Begin:output_type -> bsql.XactResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_odbc_proto_init() }
func file_odbc_proto_init() {
	if File_odbc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_odbc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DummyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odbc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XactRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odbc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XactResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_odbc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_odbc_proto_goTypes,
		DependencyIndexes: file_odbc_proto_depIdxs,
		MessageInfos:      file_odbc_proto_msgTypes,
	}.Build()
	File_odbc_proto = out.File
	file_odbc_proto_rawDesc = nil
	file_odbc_proto_goTypes = nil
	file_odbc_proto_depIdxs = nil
}
