// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: odbc.proto

package odbc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Datatype int32

const (
	Datatype_BYTEARRAY Datatype = 0
	Datatype_STRING    Datatype = 1
	Datatype_INT8      Datatype = 2
	Datatype_UINT8     Datatype = 3
	Datatype_INT16     Datatype = 4
	Datatype_UINT16    Datatype = 5
	Datatype_INT32     Datatype = 6
	Datatype_UINT32    Datatype = 7
	Datatype_INT64     Datatype = 8
	Datatype_UINT64    Datatype = 9
	Datatype_FLOAT32   Datatype = 10
	Datatype_FLOAT64   Datatype = 11
	Datatype_BOOL      Datatype = 12
	Datatype_TIMESTAMP Datatype = 13
	Datatype_UUID      Datatype = 14
)

// Enum value maps for Datatype.
var (
	Datatype_name = map[int32]string{
		0:  "BYTEARRAY",
		1:  "STRING",
		2:  "INT8",
		3:  "UINT8",
		4:  "INT16",
		5:  "UINT16",
		6:  "INT32",
		7:  "UINT32",
		8:  "INT64",
		9:  "UINT64",
		10: "FLOAT32",
		11: "FLOAT64",
		12: "BOOL",
		13: "TIMESTAMP",
		14: "UUID",
	}
	Datatype_value = map[string]int32{
		"BYTEARRAY": 0,
		"STRING":    1,
		"INT8":      2,
		"UINT8":     3,
		"INT16":     4,
		"UINT16":    5,
		"INT32":     6,
		"UINT32":    7,
		"INT64":     8,
		"UINT64":    9,
		"FLOAT32":   10,
		"FLOAT64":   11,
		"BOOL":      12,
		"TIMESTAMP": 13,
		"UUID":      14,
	}
)

func (x Datatype) Enum() *Datatype {
	p := new(Datatype)
	*p = x
	return p
}

func (x Datatype) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Datatype) Descriptor() protoreflect.EnumDescriptor {
	return file_odbc_proto_enumTypes[0].Descriptor()
}

func (Datatype) Type() protoreflect.EnumType {
	return &file_odbc_proto_enumTypes[0]
}

func (x Datatype) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Datatype.Descriptor instead.
func (Datatype) EnumDescriptor() ([]byte, []int) {
	return file_odbc_proto_rawDescGZIP(), []int{0}
}

type DummyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DummyRequest) Reset() {
	*x = DummyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odbc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DummyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyRequest) ProtoMessage() {}

func (x *DummyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_odbc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyRequest.ProtoReflect.Descriptor instead.
func (*DummyRequest) Descriptor() ([]byte, []int) {
	return file_odbc_proto_rawDescGZIP(), []int{0}
}

type InitializationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *InitializationRequest) Reset() {
	*x = InitializationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odbc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializationRequest) ProtoMessage() {}

func (x *InitializationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_odbc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializationRequest.ProtoReflect.Descriptor instead.
func (*InitializationRequest) Descriptor() ([]byte, []int) {
	return file_odbc_proto_rawDescGZIP(), []int{1}
}

func (x *InitializationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *InitializationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JWT    string `protobuf:"bytes,2,opt,name=j_w_t,json=jWT,proto3" json:"j_w_t,omitempty"`
}

func (x *AuthPacket) Reset() {
	*x = AuthPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odbc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthPacket) ProtoMessage() {}

func (x *AuthPacket) ProtoReflect() protoreflect.Message {
	mi := &file_odbc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthPacket.ProtoReflect.Descriptor instead.
func (*AuthPacket) Descriptor() ([]byte, []int) {
	return file_odbc_proto_rawDescGZIP(), []int{2}
}

func (x *AuthPacket) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AuthPacket) GetJWT() string {
	if x != nil {
		return x.JWT
	}
	return ""
}

type XactRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth           *AuthPacket `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	IsolationLevel int32       `protobuf:"varint,2,opt,name=isolation_level,json=isolationLevel,proto3" json:"isolation_level,omitempty"`
	ReadOnly       bool        `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
}

func (x *XactRequest) Reset() {
	*x = XactRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odbc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XactRequest) ProtoMessage() {}

func (x *XactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_odbc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XactRequest.ProtoReflect.Descriptor instead.
func (*XactRequest) Descriptor() ([]byte, []int) {
	return file_odbc_proto_rawDescGZIP(), []int{3}
}

func (x *XactRequest) GetAuth() *AuthPacket {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *XactRequest) GetIsolationLevel() int32 {
	if x != nil {
		return x.IsolationLevel
	}
	return 0
}

func (x *XactRequest) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type XactResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth   *AuthPacket `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	XactId uint64      `protobuf:"varint,2,opt,name=xact_id,json=xactId,proto3" json:"xact_id,omitempty"` //    bool   success = 2;
}

func (x *XactResponse) Reset() {
	*x = XactResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odbc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XactResponse) ProtoMessage() {}

func (x *XactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_odbc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XactResponse.ProtoReflect.Descriptor instead.
func (*XactResponse) Descriptor() ([]byte, []int) {
	return file_odbc_proto_rawDescGZIP(), []int{4}
}

func (x *XactResponse) GetAuth() *AuthPacket {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *XactResponse) GetXactId() uint64 {
	if x != nil {
		return x.XactId
	}
	return 0
}

type ExecRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth      *AuthPacket `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Statement string      `protobuf:"bytes,2,opt,name=statement,proto3" json:"statement,omitempty"`
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odbc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_odbc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_odbc_proto_rawDescGZIP(), []int{5}
}

func (x *ExecRequest) GetAuth() *AuthPacket {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *ExecRequest) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

type ExecResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth         *AuthPacket `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Response     string      `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	InsertId     int64       `protobuf:"varint,3,opt,name=insert_id,json=insertId,proto3" json:"insert_id,omitempty"`
	AffectedRows int64       `protobuf:"varint,4,opt,name=affected_rows,json=affectedRows,proto3" json:"affected_rows,omitempty"`
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odbc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_odbc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_odbc_proto_rawDescGZIP(), []int{6}
}

func (x *ExecResponse) GetAuth() *AuthPacket {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *ExecResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ExecResponse) GetInsertId() int64 {
	if x != nil {
		return x.InsertId
	}
	return 0
}

func (x *ExecResponse) GetAffectedRows() int64 {
	if x != nil {
		return x.AffectedRows
	}
	return 0
}

type QueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth      *AuthPacket `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Statement string      `protobuf:"bytes,2,opt,name=statement,proto3" json:"statement,omitempty"`
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odbc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_odbc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_odbc_proto_rawDescGZIP(), []int{7}
}

func (x *QueryRequest) GetAuth() *AuthPacket {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *QueryRequest) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth       *AuthPacket `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	RespLength int32       `protobuf:"varint,2,opt,name=resp_length,json=respLength,proto3" json:"resp_length,omitempty"`
	RespSchema *Schema     `protobuf:"bytes,3,opt,name=resp_schema,json=respSchema,proto3" json:"resp_schema,omitempty"`
	ResultSet  []*Row      `protobuf:"bytes,4,rep,name=result_set,json=resultSet,proto3" json:"result_set,omitempty"`
	Done       bool        `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odbc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_odbc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_odbc_proto_rawDescGZIP(), []int{8}
}

func (x *QueryResponse) GetAuth() *AuthPacket {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *QueryResponse) GetRespLength() int32 {
	if x != nil {
		return x.RespLength
	}
	return 0
}

func (x *QueryResponse) GetRespSchema() *Schema {
	if x != nil {
		return x.RespSchema
	}
	return nil
}

func (x *QueryResponse) GetResultSet() []*Row {
	if x != nil {
		return x.ResultSet
	}
	return nil
}

func (x *QueryResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type Schema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName              string     `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	ColumnName             []string   `protobuf:"bytes,2,rep,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`
	ColumnType             []Datatype `protobuf:"varint,3,rep,packed,name=column_type,json=columnType,proto3,enum=bsql.Datatype" json:"column_type,omitempty"`
	ColumnSize             []int64    `protobuf:"varint,4,rep,packed,name=column_size,json=columnSize,proto3" json:"column_size,omitempty"`
	ColumnIsNullableBitmap []byte     `protobuf:"bytes,5,opt,name=column_is_nullable_bitmap,json=columnIsNullableBitmap,proto3" json:"column_is_nullable_bitmap,omitempty"`
}

func (x *Schema) Reset() {
	*x = Schema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odbc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_odbc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_odbc_proto_rawDescGZIP(), []int{9}
}

func (x *Schema) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *Schema) GetColumnName() []string {
	if x != nil {
		return x.ColumnName
	}
	return nil
}

func (x *Schema) GetColumnType() []Datatype {
	if x != nil {
		return x.ColumnType
	}
	return nil
}

func (x *Schema) GetColumnSize() []int64 {
	if x != nil {
		return x.ColumnSize
	}
	return nil
}

func (x *Schema) GetColumnIsNullableBitmap() []byte {
	if x != nil {
		return x.ColumnIsNullableBitmap
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Columns          [][]byte `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	NullColumnBitmap []byte   `protobuf:"bytes,2,opt,name=null_column_bitmap,json=nullColumnBitmap,proto3" json:"null_column_bitmap,omitempty"` // Null flag? bitmap?
}

func (x *Row) Reset() {
	*x = Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odbc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_odbc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_odbc_proto_rawDescGZIP(), []int{10}
}

func (x *Row) GetColumns() [][]byte {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Row) GetNullColumnBitmap() []byte {
	if x != nil {
		return x.NullColumnBitmap
	}
	return nil
}

type CloseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odbc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_odbc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_odbc_proto_rawDescGZIP(), []int{11}
}

type LoadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoadRequest) Reset() {
	*x = LoadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odbc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRequest) ProtoMessage() {}

func (x *LoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_odbc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRequest.ProtoReflect.Descriptor instead.
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return file_odbc_proto_rawDescGZIP(), []int{12}
}

type LoadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoadResponse) Reset() {
	*x = LoadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odbc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadResponse) ProtoMessage() {}

func (x *LoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_odbc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadResponse.ProtoReflect.Descriptor instead.
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return file_odbc_proto_rawDescGZIP(), []int{13}
}

var File_odbc_proto protoreflect.FileDescriptor

var file_odbc_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6f, 0x64, 0x62, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x73,
	0x71, 0x6c, 0x22, 0x0e, 0x0a, 0x0c, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x4f, 0x0a, 0x15, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x39, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x05, 0x6a, 0x5f,
	0x77, 0x5f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6a, 0x57, 0x54, 0x22, 0x79,
	0x0a, 0x0b, 0x58, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a,
	0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x73,
	0x71, 0x6c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x04, 0x61,
	0x75, 0x74, 0x68, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x69, 0x73,
	0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1b, 0x0a, 0x09,
	0x72, 0x65, 0x61, 0x64, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x72, 0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x22, 0x4d, 0x0a, 0x0c, 0x58, 0x61, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x61, 0x75, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x73, 0x71, 0x6c, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12,
	0x17, 0x0a, 0x07, 0x78, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x78, 0x61, 0x63, 0x74, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x0b, 0x45, 0x78, 0x65, 0x63,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x73, 0x71, 0x6c, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x92, 0x01, 0x0a, 0x0c,
	0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04,
	0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x73, 0x71,
	0x6c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x04, 0x61, 0x75,
	0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x61,
	0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x6f, 0x77, 0x73,
	0x22, 0x52, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x24, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x62, 0x73, 0x71, 0x6c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x22, 0xc3, 0x01, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x73, 0x71, 0x6c, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x1f, 0x0a, 0x0b,
	0x72, 0x65, 0x73, 0x70, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x70, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x2d, 0x0a,
	0x0b, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x73, 0x71, 0x6c, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x52, 0x0a, 0x72, 0x65, 0x73, 0x70, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x28, 0x0a, 0x0a,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x62, 0x73, 0x71, 0x6c, 0x2e, 0x72, 0x6f, 0x77, 0x52, 0x09, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x53, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x22, 0xd5, 0x01, 0x0a, 0x06, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x62, 0x73, 0x71,
	0x6c, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x74, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x39, 0x0a, 0x19, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x5f, 0x69, 0x73, 0x5f, 0x6e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x62, 0x69,
	0x74, 0x6d, 0x61, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x16, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x49, 0x73, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x69, 0x74, 0x6d,
	0x61, 0x70, 0x22, 0x4d, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x6e, 0x75, 0x6c, 0x6c, 0x5f, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x5f, 0x62, 0x69, 0x74, 0x6d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x10, 0x6e, 0x75, 0x6c, 0x6c, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x42, 0x69, 0x74, 0x6d, 0x61,
	0x70, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2a, 0xbc, 0x01, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0d,
	0x0a, 0x09, 0x42, 0x59, 0x54, 0x45, 0x41, 0x52, 0x52, 0x41, 0x59, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x54,
	0x38, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x49, 0x4e, 0x54, 0x38, 0x10, 0x03, 0x12, 0x09,
	0x0a, 0x05, 0x49, 0x4e, 0x54, 0x31, 0x36, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x49, 0x4e,
	0x54, 0x31, 0x36, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e, 0x54, 0x33, 0x32, 0x10, 0x06,
	0x12, 0x0a, 0x0a, 0x06, 0x55, 0x49, 0x4e, 0x54, 0x33, 0x32, 0x10, 0x07, 0x12, 0x09, 0x0a, 0x05,
	0x49, 0x4e, 0x54, 0x36, 0x34, 0x10, 0x08, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x49, 0x4e, 0x54, 0x36,
	0x34, 0x10, 0x09, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x33, 0x32, 0x10, 0x0a,
	0x12, 0x0b, 0x0a, 0x07, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x36, 0x34, 0x10, 0x0b, 0x12, 0x08, 0x0a,
	0x04, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x0c, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x49, 0x4d, 0x45, 0x53,
	0x54, 0x41, 0x4d, 0x50, 0x10, 0x0d, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x10, 0x0e,
	0x32, 0xd5, 0x02, 0x0a, 0x0a, 0x4d, 0x44, 0x42, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x47, 0x0a, 0x14, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x62, 0x73, 0x71, 0x6c, 0x2e, 0x49,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x62, 0x73, 0x71, 0x6c, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x05, 0x42, 0x65, 0x67, 0x69,
	0x6e, 0x12, 0x11, 0x2e, 0x62, 0x73, 0x71, 0x6c, 0x2e, 0x58, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x62, 0x73, 0x71, 0x6c, 0x2e, 0x58, 0x61, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x05, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x12, 0x12, 0x2e, 0x62, 0x73, 0x71, 0x6c, 0x2e, 0x44, 0x75, 0x6d, 0x6d, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x62, 0x73, 0x71, 0x6c, 0x2e, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2f,
	0x0a, 0x04, 0x45, 0x78, 0x65, 0x63, 0x12, 0x11, 0x2e, 0x62, 0x73, 0x71, 0x6c, 0x2e, 0x45, 0x78,
	0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x62, 0x73, 0x71, 0x6c,
	0x2e, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x34, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x12, 0x2e, 0x62, 0x73, 0x71, 0x6c, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x62,
	0x73, 0x71, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x31, 0x0a, 0x04, 0x4c, 0x6f, 0x61, 0x64, 0x12, 0x11, 0x2e,
	0x62, 0x73, 0x71, 0x6c, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x62, 0x73, 0x71, 0x6c, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x6c,
	0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x6f, 0x64, 0x62, 0x63,
	0x2f, 0x6d, 0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x42, 0x75, 0x66,
	0x66, 0x65, 0x72, 0x73, 0x2f, 0x6f, 0x64, 0x62, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_odbc_proto_rawDescOnce sync.Once
	file_odbc_proto_rawDescData = file_odbc_proto_rawDesc
)

func file_odbc_proto_rawDescGZIP() []byte {
	file_odbc_proto_rawDescOnce.Do(func() {
		file_odbc_proto_rawDescData = protoimpl.X.CompressGZIP(file_odbc_proto_rawDescData)
	})
	return file_odbc_proto_rawDescData
}

var file_odbc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_odbc_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_odbc_proto_goTypes = []interface{}{
	(Datatype)(0),                 // 0: bsql.datatype
	(*DummyRequest)(nil),          // 1: bsql.DummyRequest
	(*InitializationRequest)(nil), // 2: bsql.InitializationRequest
	(*AuthPacket)(nil),            // 3: bsql.authPacket
	(*XactRequest)(nil),           // 4: bsql.XactRequest
	(*XactResponse)(nil),          // 5: bsql.XactResponse
	(*ExecRequest)(nil),           // 6: bsql.ExecRequest
	(*ExecResponse)(nil),          // 7: bsql.ExecResponse
	(*QueryRequest)(nil),          // 8: bsql.QueryRequest
	(*QueryResponse)(nil),         // 9: bsql.QueryResponse
	(*Schema)(nil),                // 10: bsql.schema
	(*Row)(nil),                   // 11: bsql.row
	(*CloseResponse)(nil),         // 12: bsql.CloseResponse
	(*LoadRequest)(nil),           // 13: bsql.LoadRequest
	(*LoadResponse)(nil),          // 14: bsql.LoadResponse
}
var file_odbc_proto_depIdxs = []int32{
	3,  // 0: bsql.XactRequest.auth:type_name -> bsql.authPacket
	3,  // 1: bsql.XactResponse.auth:type_name -> bsql.authPacket
	3,  // 2: bsql.ExecRequest.auth:type_name -> bsql.authPacket
	3,  // 3: bsql.ExecResponse.auth:type_name -> bsql.authPacket
	3,  // 4: bsql.QueryRequest.auth:type_name -> bsql.authPacket
	3,  // 5: bsql.QueryResponse.auth:type_name -> bsql.authPacket
	10, // 6: bsql.QueryResponse.resp_schema:type_name -> bsql.schema
	11, // 7: bsql.QueryResponse.result_set:type_name -> bsql.row
	0,  // 8: bsql.schema.column_type:type_name -> bsql.datatype
	2,  // 9: bsql.MDBService.InitializeConnection:input_type -> bsql.InitializationRequest
	4,  // 10: bsql.MDBService.Begin:input_type -> bsql.XactRequest
	1,  // 11: bsql.MDBService.Close:input_type -> bsql.DummyRequest
	6,  // 12: bsql.MDBService.Exec:input_type -> bsql.ExecRequest
	8,  // 13: bsql.MDBService.Query:input_type -> bsql.QueryRequest
	13, // 14: bsql.MDBService.Load:input_type -> bsql.LoadRequest
	3,  // 15: bsql.MDBService.InitializeConnection:output_type -> bsql.authPacket
	5,  // 16: bsql.MDBService.Begin:output_type -> bsql.XactResponse
	12, // 17: bsql.MDBService.Close:output_type -> bsql.CloseResponse
	7,  // 18: bsql.MDBService.Exec:output_type -> bsql.ExecResponse
	9,  // 19: bsql.MDBService.Query:output_type -> bsql.QueryResponse
	14, // 20: bsql.MDBService.Load:output_type -> bsql.LoadResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_odbc_proto_init() }
func file_odbc_proto_init() {
	if File_odbc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_odbc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DummyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odbc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odbc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odbc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XactRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odbc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XactResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odbc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odbc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odbc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odbc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odbc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Schema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odbc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odbc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odbc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odbc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_odbc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_odbc_proto_goTypes,
		DependencyIndexes: file_odbc_proto_depIdxs,
		EnumInfos:         file_odbc_proto_enumTypes,
		MessageInfos:      file_odbc_proto_msgTypes,
	}.Build()
	File_odbc_proto = out.File
	file_odbc_proto_rawDesc = nil
	file_odbc_proto_goTypes = nil
	file_odbc_proto_depIdxs = nil
}
