// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package odbc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MDBServiceClient is the client API for MDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MDBServiceClient interface {
	// Begin: Start Transaction
	Begin(ctx context.Context, in *XactRequest, opts ...grpc.CallOption) (*XactResponse, error)
}

type mDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMDBServiceClient(cc grpc.ClientConnInterface) MDBServiceClient {
	return &mDBServiceClient{cc}
}

func (c *mDBServiceClient) Begin(ctx context.Context, in *XactRequest, opts ...grpc.CallOption) (*XactResponse, error) {
	out := new(XactResponse)
	err := c.cc.Invoke(ctx, "/bsql.MDBService/Begin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MDBServiceServer is the server API for MDBService service.
// All implementations must embed UnimplementedMDBServiceServer
// for forward compatibility
type MDBServiceServer interface {
	// Begin: Start Transaction
	Begin(context.Context, *XactRequest) (*XactResponse, error)
	mustEmbedUnimplementedMDBServiceServer()
}

// UnimplementedMDBServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMDBServiceServer struct {
}

func (UnimplementedMDBServiceServer) Begin(context.Context, *XactRequest) (*XactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Begin not implemented")
}
func (UnimplementedMDBServiceServer) mustEmbedUnimplementedMDBServiceServer() {}

// UnsafeMDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MDBServiceServer will
// result in compilation errors.
type UnsafeMDBServiceServer interface {
	mustEmbedUnimplementedMDBServiceServer()
}

func RegisterMDBServiceServer(s grpc.ServiceRegistrar, srv MDBServiceServer) {
	s.RegisterService(&MDBService_ServiceDesc, srv)
}

func _MDBService_Begin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MDBServiceServer).Begin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bsql.MDBService/Begin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MDBServiceServer).Begin(ctx, req.(*XactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MDBService_ServiceDesc is the grpc.ServiceDesc for MDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bsql.MDBService",
	HandlerType: (*MDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Begin",
			Handler:    _MDBService_Begin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "odbc.proto",
}
